import html2canvas from 'html2canvas'

export async function generateShareImage(elementId) {
  const element = document.getElementById(elementId)
  if (!element) return null
  
  // Clone the node to style it slightly differently for the image if needed
  // But for now, we just take a snapshot of the raw result card
  
  // Create an invisible wrapper to ensure dark background is captured correctly
  const wrapper = document.createElement('div')
  wrapper.style.position = 'absolute'
  wrapper.style.left = '-9999px'
  wrapper.style.top = '0'
  wrapper.style.width = '375px' // Fixed mobile width for sharing
  wrapper.style.background = '#0a0a0c' // Dark background from style.css
  wrapper.style.padding = '20px'
  wrapper.style.borderRadius = '16px'
  
  const clone = element.cloneNode(true)
  wrapper.appendChild(clone)
  document.body.appendChild(wrapper)
  
  // Tweak clone styles specifically for the image
  clone.style.margin = '0'
  clone.style.boxShadow = 'none'
  
  // Add a watermark
  const watermark = document.createElement('div')
  watermark.style.textAlign = 'center'
  watermark.style.color = 'rgba(255, 255, 255, 0.4)'
  watermark.style.fontSize = '12px'
  watermark.style.marginTop = '20px'
  watermark.style.paddingTop = '10px'
  watermark.style.borderTop = '1px solid rgba(255, 255, 255, 0.1)'
  watermark.innerText = 'Generated by NumFate Oracle'
  clone.appendChild(watermark)

  try {
    const canvas = await html2canvas(wrapper, {
      backgroundColor: '#0a0a0c',
      scale: 2, // High resolution
      useCORS: true,
      logging: false,
    })
    
    // Convert to Base64 image
    const dataUrl = canvas.toDataURL('image/png')
    return dataUrl
  } catch (err) {
    console.error('Failed to generate image:', err)
    return null
  } finally {
    document.body.removeChild(wrapper)
  }
}

export function downloadImage(dataUrl, filename = 'numfate-destiny.png') {
  const link = document.createElement('a')
  link.href = dataUrl
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}
